### ISSUE TITLE
Bug: DriftProtocol requires protobuf 3.11.1 which incompatible with anomalib

### ISSUE THREAD

**Issue by mmaciejak** [panda-official/DriftProtocol#3]
### What happened?

When creating drift service from cookiecutter template and trying to run Cflow model with anomalib:  https://github.com/openvinotoolkit/anomalib. I got into a dependency conflict between DritProtocol that needs protobuf 3.11.1, and dependency of anomalib: wandb that requires protobuf>=3.12.0,<4.0dev. Drift protocol throws a wrong version exception when protobuf is not 3.11.1. With 3.11.1 error from anomalib is:

### Version

0.1.0

### OS

Linux

### Programming Language

Python

### Snippet to repeat the bug

`from anomalib.models.cflow.lightning_model import Cflow`

### Logs

```
Exception has occurred: AttributeError
module 'google.protobuf.descriptor' has no attribute 'internal_create_key'
  File "/home/panda/AI_service/bbraun-anomaly_detection/app/models.py", line 1, in <module>
    from anomalib.models.cflow.lightning_model import Cflow
  File "/home/panda/AI_service/bbraun-anomaly_detection/app/service.py", line 19, in <module>
    from app.models import CflowAnomalyDetector, BlobDetector
  File "/home/panda/AI_service/bbraun-anomaly_detection/app/_main.py", line 3, in <module>
    from app.service import main`
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atimin** [comment]
@mmaciejak I believe I've fixed the issue here #5. However, I'd like your commitment that it works on your side. Could take `drift-539` on your machine and install from source: In python folder: `pip install .`
